#!/usr/bin/python

import os
import psutil
import signal
import time
import subprocess
from datetime import datetime

path = '/coverage/develop/.fuzzing.latest/'

while True:
    for proc in psutil.process_iter():
        if 'light-node' == proc.name():
            date = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            print(f'[{date}] Sending signal to light-node ({proc.pid})...')
            os.kill(proc.pid, signal.SIGUSR2)
            time.sleep(1)
            commands = f"""rm -f *.gcov
            lcov --directory /tezedge/target/fuzz/deps/ --capture --output-file app.info --gcov-tool /scripts/gcov.sh
            mkdir "{path}/p2p-rpc-fuzzers" "{path}/p2p-rpc-fuzzers/lcov/"
            genhtml app.info -o "{path}/p2p-rpc-fuzzers/lcov/"
            python /scripts/lcov2kcov.py
            python /scripts/lcov2kcov_index.py
            """.replace('\n', ';')
            subprocess.run(commands, shell=True)
            break

    time.sleep(60 * 5)
