#!/bin/sh

docker run -d -m=64g --cap-add=SYS_PTRACE --cpuset-cpus=0-16 --network=fuzznet --ip=172.18.0.101 -v $(pwd)/_data:/data -v $(pwd)/log:/log -v /var/lib/fuzzing-data/reports/:/coverage -ti fuzz_target
