#!/usr/bin/python

import sys
from time import sleep
from xmlrpc.client import ServerProxy

if len(sys.argv) != 3 \
  or sys.argv[1] not in ('node', 'coverage', 'httpd') \
  or sys.argv[2] not in ('out', 'err'):
   print(f'use: {sys.argv[0]} (node|coverage) (out|err)') 
   exit(1)

server = ServerProxy('http://172.18.0.101:9001/RPC2')
func = {
    'out': server.supervisor.tailProcessStdoutLog,
    'err': server.supervisor.tailProcessStderrLog,
}[sys.argv[2]]

off = 0
pending = True

while True:
    data, off, pending = func(sys.argv[1], off, 512)
    print(data, end='', flush=True)

    if not pending:
        sleep(1)
